src/labsite/accounting/urls.py
# flake8: noqa
from django.conf.urls import url

from . import views


app_name = 'accounting'

urlpatterns = [

    # Accounting HomePage
    url(r'^$', views.HomePageView.as_view(), name='home'),

    # Dashboard Views
    url(r'^(?P<business_unit>\d+)/dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^(?P<business_unit>\d+)/dashboard/fy-(?P<fiscal_year>\d+)/$', views.DashboardView.as_view(), name='dashboard'),

    # Expense Views
    url(r'^(?P<business_unit>\d+)/reconcile/$', views.MonthlyReconcileView.as_view(), name='reconcile'),
    url(r'^(?P<business_unit>\d+)/reconcile/fy-(?P<fiscal_year>\d+)/$', views.MonthlyReconcileView.as_view(), name='reconcile'),

    # Contracts View
    url(r'^(?P<business_unit>\d+)/contracts/$', views.ContractsView.as_view(), name='contracts'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/$', views.ContractDetailView.as_view(), name='contract_detail'),

    # Prospects View
    url(r'^(?P<business_unit>\d+)/prospects/$', views.ProspectsView.as_view(), name='prospects'),

    # Settings Views
    url(r'^(?P<business_unit>\d+)/settings/business_unit/$', views.BusinessUnitSettingsPageView.as_view(), name='business_unit_settings'),
    url(r'^(?P<business_unit>\d+)/settings/user_team_roles/$', views.UserTeamRolesSettingsPageView.as_view(), name='user_team_roles_settings'),

    # Business Unit Forms
    url(r'^create/$', views.BusinessUnitCreateView.as_view(), name='create_business_unit'),
    url(r'^(?P<business_unit>\d+)/update/$', views.BusinessUnitUpdateView.as_view(), name='update_business_unit'),
    url(r'^(?P<business_unit>\d+)/delete/$', views.BusinessUnitDeleteView.as_view(), name='delete_business_unit'),

    # Contracts Forms
    url(r'^(?P<business_unit>\d+)/contracts/create/$', views.ContractCreateView.as_view(), name='create_contract'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/update/$', views.ContractUpdateView.as_view(), name='update_contract'),

    # Prospect Forms
    url(r'^(?P<business_unit>\d+)/prospects/create/$', views.ProspectCreateView.as_view(), name='create_prospect'),

    # Invoice Forms
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/create/$', views.InvoiceCreateView.as_view(), name='create_invoice'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/(?P<invoice>\d+)/update/$', views.InvoiceUpdateView.as_view(), name='update_invoice'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/(?P<invoice>\d+)/delete/$', views.InvoiceDeleteView.as_view(), name='delete_invoice'),

    # User Team Role Forms
    url(r'^(?P<business_unit>\d+)/user_team_role/create/$', views.UserTeamRoleCreateView.as_view(), name='create_user_team_role'),
    url(r'^(?P<business_unit>\d+)/user_team_role/(?P<user_team_role>\d+)/update/$', views.UserTeamRoleUpdateView.as_view(), name='update_user_team_role'),
    url(r'^(?P<business_unit>\d+)/user_team_role/(?P<user_team_role>\d+)/delete/$', views.UserTeamRoleDeleteView.as_view(), name='delete_user_team_role'),

    # Invoice Print Page
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/(?P<invoice>\d+)/print/$', views.InvoicePrintView.as_view(), name='print_invoice'),
]

src/labsite/foodapp/urls.py
from django.conf.urls import url

from . import views


app_name = 'foodapp'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),

    url(r'^billing/cards/$', views.StripeCardListView.as_view(), name='stripe_card_list'),
    url(r'^billing/cards/create$', views.StripeCreateView.as_view(), name='stripe_card_create'),
    url(r'^billing/cards/create$', views.StripeCreateView.as_view(), name='stripe_customer_create'),
    url(r'^billing/cards/delete/(?P<card_id>\w+)/$', views.StripeCardDeleteView.as_view(), name='stripe_card_delete'),
    url(r'^billing/cards/update/(?P<card_id>\w+)/$', views.StripeCardUpdateView.as_view(), name='stripe_card_update'),

    url(r'^billing/invoices/$', views.StripeInvoiceView.as_view(), name='stripe_invoices'),

    url(r'^burrito-projections/$', views.BurritoProjectionView.as_view(), name='burrito_projections'),

    url(r'^orders/$', views.OrderListView.as_view(), name='orders'),
    url(r'^orders/unpaid/$', views.UnpaidOrdersView.as_view(), name='unpaid_orders'),
    url(r'^orders/user/(?P<username>\w+)/$', views.UserOrderView.as_view(), name='user_orders'),
    url(r'^orders/last_month/$', views.last_month_view, name='last_month_view'),
    url(r'^orders/leaderboard/$', views.LeaderboardView.as_view(), name='leaderboard'),
    url(r'^orders/(?P<year>\d{4})/(?P<month>\d{2})/$', views.MonthOrdersView.as_view(), name='month_orders'),
    url(r'^orders/super/(?P<year>\d{4})/(?P<month>\d{2})/$', views.SuperMonthOrdersView.as_view(), name='super_month_orders'),  # noqa: E501
]

src/labsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = 'labsite/home.html'


urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='home'),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Auth urls
    url(r'^', include('labsite.accounts.auth.urls')),

    url(r'^accounts/', include('registration_invite.urls.activation')),

    # App urls
    url(r'^lunch/', include('labsite.foodapp.urls')),
    url(r'^worklog/', include('labsite.worklog.urls')),
    url(r'^accounting/', include('labsite.accounting.urls')),
]

src/labsite/worklog/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

from . import views
from .api import views as api_views


router = DefaultRouter()
router.register(r'workdays', api_views.WorkDayViewSet)
router.register(r'workitems', api_views.WorkItemViewSet)
router.register(r'users', api_views.UserViewSet)
router.register(r'jobs', api_views.JobViewSet)


DATEMIN = r'(?P<datemin>\d{4}-\d{2}-\d{2})'
DATEMAX = r'(?P<datemax>\d{4}-\d{2}-\d{2})'
# accepts:  date_date   or   date_   or   _date
DATERANGE1 = '(?:' + DATEMIN + '_' + DATEMAX + '?)'
DATERANGE2 = '(?:_' + DATEMAX + ')'

USERNAME = r'(?P<username>[a-zA-Z0-9]+)'
# JOBID = r'(?:_job_(?P<jobid>[0-9]+))'


app_name = 'worklog'

urlpatterns = [
    url(r'^$', views.HomepageView.as_view(), {}, name='home'),
    url(r'^(?P<date>\d{4}-\d{2}-\d{2})/$', views.WorkItemView.as_view(), name='date'),
    url(r'^today/$', views.CurrentDateRedirectView.as_view(), name='today'),
    url(r'^add/$', views.CurrentDateRedirectView.as_view(), name='add'),

    url(r'^view/$', views.WorklogView.as_view(), {}, name='view'),
    url(r'^view/today/$', views.WorklogView.as_view(), {'datemin': 'today', 'datemax': 'today'}, name='view-today'),

    url(r'^view/' + DATERANGE1 + '/$', views.WorklogView.as_view(), name='view-daterange'),
    url(r'^view/' + DATERANGE2 + '/$', views.WorklogView.as_view(), name='view-datemax'),
    url(r'^view/' + USERNAME + '/$', views.WorklogView.as_view(), name='view-user'),
    url(r'^view/' + USERNAME + '/today/$', views.WorklogView.as_view(), {'datemin': 'today', 'datemax': 'today'}, name='view-user-today'),  # noqa: E501
    url(r'^view/' + USERNAME + '/' + DATERANGE1 + '/$', views.WorklogView.as_view(), name='view-user-daterange'),
    url(r'^view/' + USERNAME + '/' + DATERANGE2 + '/$', views.WorklogView.as_view(), name='view-user-datemax'),

    url(r'^report/$', views.ReportView.as_view(), name='report_url'),
    url(r'^chart/$', views.ChartView.as_view(), name='chart_url'),
    url(r'^chart/job/$', views.JobDataView.as_view(), name='job_data_url'),

    url(r'^api/', include(router.urls)),
]

src/labsite/accounting/models.py
from datetime import date
from decimal import Decimal

from django.apps import apps
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q, Sum
from django.db.models import Value as V
from django.db.models.functions import Coalesce
from django.utils.translation import ugettext_lazy as _
from django_fsm import FSMField, transition

from labsite.utils import choices

from .utils import Month, get_or_none


User = settings.AUTH_USER_MODEL


MONTHS = choices((
    (1, _('January')),
    (2, _('February')),
    (3, _('March')),
    (4, _('April')),
    (5, _('May')),
    (6, _('June')),
    (7, _('July')),
    (8, _('August')),
    (9, _('September')),
    (10, _('October')),
    (11, _('November')),
    (12, _('December')),
))


def current_year():
    return date.today().year


def validate_positive(value):
    if value is not None and value < 0:
        raise ValidationError(_('Value must be a positive number.'))


def validate_percentile(value):
    if value is not None and value > 1:
        raise ValidationError(_('Value must be less than or equal to 1'))


class BusinessUnit(models.Model):
    name = models.CharField(max_length=64)
    account_number = models.CharField(max_length=12)

    users = models.ManyToManyField(User, through='UserTeamRole', related_name='business_units')

    def __str__(self):
        return self.name


class UserTeamRole(models.Model):
    ROLES = choices((
        ('MANAGER', _('Manager')),
        ('VIEWER', _('Viewer')),
    ))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    role = models.CharField(max_length=12, choices=ROLES, default=ROLES.VIEWER)

    class Meta:
        unique_together = ['user', 'business_unit']

    def __str__(self):
        return '%s is a %s of %s' % (self.user.username, self.role, self.business_unit.name)


class Contract(models.Model):
    STATES = choices((
        ('NEW', _('New')),
        ('ACTIVE', _('Active')),
        ('COMPLETE', _('Complete')),
    ))
    TYPES = choices((
        ('FIXED', _('Fixed')),
        ('HOURLY', _('Hourly')),
    ))
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    contract_id = models.CharField(max_length=64, unique=True, verbose_name=_("contract ID"))
    name = models.CharField(max_length=255, verbose_name=_("contract name"))
    customer = models.CharField(max_length=255, verbose_name=_("Customer"), blank=True)
    description = models.CharField(max_length=255, verbose_name=_("Description"), blank=True)
    start_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0, validators=[validate_positive])
    state = FSMField(max_length=8, choices=STATES, default=STATES.NEW)
    type = models.CharField(max_length=8, choices=TYPES)
    notes = models.TextField(verbose_name="Notes", blank=True)

    def __str__(self):
        return '%s: %s' % (self.contract_id, self.name)

    def outstanding_amount(self):
        total_received = self.invoice_set \
            .filter(state=Invoice.STATES.RECEIVED) \
            .aggregate(v=Coalesce(Sum('actual_amount'), V(Decimal(0))))['v']
        return self.amount - total_received

    def get_invoices_expected_total(self):
        aggregate = models.Sum(
            'expected_amount',
            output_field=models.DecimalField(max_digits=10, decimal_places=2, default=0)
        )
        return self.invoice_set.all().aggregate(amount=aggregate)['amount']

    def get_unreceived_invoices(self):
        return self.invoice_set.filter(actual_amount=None) | \
            self.invoice_set.exclude(state=Invoice.STATES.RECEIVED)

    def has_invoice(self):
        return self.invoice_set.exists()

    def amount_matches_invoices(self):
        # The expected amount of all invoices should match the contract's dollar amount.
        return self.amount == self.get_invoices_expected_total()

    def all_invoices_received(self):
        return not self.get_unreceived_invoices().exists()

    @transition(field=state, source=STATES.NEW, target=STATES.ACTIVE, conditions=[has_invoice, amount_matches_invoices])
    def activate(self):
        """
        Mark the Contract as active.
        """

        for idx, invoice in enumerate(self.invoice_set.order_by('expected_invoice_date'), start=1):
            invoice.invoice_id = "%s-%02d" % (self.contract_id, idx)
            invoice.save()

    @transition(field=state, source=STATES.ACTIVE, target=STATES.COMPLETE, conditions=[all_invoices_received])
    def complete(self):
        """
        Mark the contract as complete.
        """


class Prospect(models.Model):
    TYPES = choices((
        ('FIXED', _('Fixed')),
        ('HOURLY', _('Hourly')),
    ))
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, verbose_name=_("Description"))
    est_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0, validators=[validate_positive])
    probability = models.FloatField(default=0, validators=[validate_positive, validate_percentile])

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class LineItem(models.Model):
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    expected_amount = models.DecimalField(max_digits=10, decimal_places=2)
    actual_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=None)

    class Meta():
        abstract = True


class Invoice(LineItem):
    STATES = choices((
        ('NOT_INVOICED', _('Not Invoiced')),
        ('INVOICED', _('Invoiced')),
        ('RECEIVED', _('Received')),
    ))
    # Invoice IDs are generated by the contract when transitioning from the 'new' to 'active' state. Although it
    # goes against general advice, the charfield is made nullable in order to bypass the uniqueness constraint.
    invoice_id = models.CharField(max_length=64, unique=True, null=True, editable=False, verbose_name=_("invoice ID"))
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    state = models.CharField(max_length=15, choices=STATES, default=STATES.NOT_INVOICED)

    expected_invoice_date = models.DateField()
    expected_payment_date = models.DateField()
    actual_invoice_date = models.DateField(null=True, blank=True)
    actual_payment_date = models.DateField(null=True, blank=True)

    class Meta:
        # The unique_together constraint soft requirement:
        # - expected invoice date is used for ordering before the ID is created.
        # - It doesn't really make sense to expect two separate invoices on the
        #   same date for the same contract.
        # - This can easily be removed if necessary
        unique_together = ('contract', 'expected_invoice_date')

    def __str__(self):
        return self.invoice_id or "Invoice: %d" % self.pk


class MonthlyQuerySet(models.QuerySet):
    # TODO: define before/after if useful

    def range(self, start, stop, inclusive=True):
        # While counterintuitive, we're mostly dealing with inclusive month ranges.
        # eg, FY 2016 starts on July 2016 and ends in June of 2017.

        # coerce date-likes to Month types.
        start, stop = Month(start), Month(stop)

        # ensure start is before stop
        if start > stop:
            start, stop = stop, start

        if inclusive:
            stop = Month.next(stop)

        return self.filter(
            Q(year=start.year, month__gte=start.month) |
            Q(year__gt=start.year, year__lt=stop.year) |
            Q(year=stop.year, month__lt=stop.month)
        )


class MonthlyReconcile(models.Model):
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)

    # Date field isn't entirely appropriate, since items are associated by month.
    month = models.SmallIntegerField(choices=MONTHS, default=MONTHS._1)
    year = models.SmallIntegerField(default=current_year)

    objects = MonthlyQuerySet.as_manager()

    class Meta:
        unique_together = ('month', 'year')
        ordering = ('-year', '-month')

    def __repr__(self):
        return '<%s: %s>' % (self.__class__.__name__, str(self), )

    def __str__(self):
        return "%4d-%02d (%s)" % (self.year, self.month, self.business_unit, )


class MonthlyBalance(LineItem):
    # Date field isn't entirely appropriate, since items are associated by month.
    month = models.SmallIntegerField(choices=MONTHS, default=MONTHS._1)
    year = models.SmallIntegerField(default=current_year)

    objects = MonthlyQuerySet.as_manager()

    class Meta:
        unique_together = ('month', 'year')
        ordering = ('-year', '-month')
        abstract = True

    def __repr__(self):
        return '<%s: %s>' % (self.__class__.__name__, str(self), )

    def __str__(self):
        return "%4d-%02d (%s)" % (self.year, self.month, self.business_unit, )


class CashBalance(MonthlyBalance):
    """
    The actual "cash on hand" balance per month.
    """
    @property
    def expected_amount(self):
        """
        Formula:
            - use *last* month's cash balance
            - add this month's billable invoices
            - subtract this month's expenses
        """
        # carry over last month's cash balance
        cash_balance = Decimal(0)
        if self.previous_cashbalance is not None:
            # preference actual cash balance over expected
            cash_balance = self.previous_cashbalance.actual_amount \
                or self.previous_cashbalance.expected_amount

        # sum all billable invoices
        income = Invoice.objects \
            .filter(
                business_unit=self.business_unit,
                expected_payment_date__year=self.year,

src/labsite/templates/accounting/base.html
{% extends "base.html" %}

{% block title %}Accounting{% endblock %}

{% load staticfiles %}

{% block app-styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/accounting/styles.css' %}"/>
{% endblock %}

{% block nav-links-left %}
{% if business_units %}
    <ul class="nav navbar-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                {% if current_business_unit %}
                {{ current_business_unit.name }}
                {% else %}Select Business Unit{% endif %}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% for business_unit in business_units %}
                    {% if business_unit.pk != current_business_unit.pk %}
                        <li><a href="{% url 'accounting:dashboard' business_unit=business_unit.pk %}">{{ business_unit.name }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if business_units|length == 1 and not current_business_unit.name %}<li class="divider"></li>
                {% elif business_units|length > 1 %}<li class="divider"></li>{% endif %}
                <li><a href="{% url 'accounting:create_business_unit' %}">Create Business Unit</a></li>
            </ul>
        </li>
    </ul>
{% endif %}
{% endblock %}

{% block app-scripts %}
    {% include "accounting/action_modal.html" %}
    <script src="{% static 'js/accounting/modal-populate.js' %}"></script>
{% endblock %}

src/labsite/templates/accounting/contract_detail.html
{% extends "accounting/base.html" %}
{% load accounting_filters %}
{% block content %}
{% with contract=contract_ctx.contract %}
<a class="btn btn-primary" style="margin-bottom: 1em;" href="{% url 'accounting:contracts' business_unit=current_business_unit.pk %}"><span class="fa fa-arrow-circle-left"> Contracts</span></a>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <h3 style="margin: auto" class="col-xs-8 col-md-10">{{ contract.name }}</h3>
            <div class="pull-right">{% include 'accounting/contract_actions.html' with size='xs' %}</div>
        </div>
    </div>
    <table class="table">
        <tr>
            <td class="col-xs-4"><b>Contracted: </b>{{ contract.amount|currency }}</td>
            <td class="col-xs-4"><b>Outstanding: </b>{{ contract.outstanding_amount|currency }}</td>
            <td class="col-xs-4"><b>Start Date: </b>{{ contract.start_date }}</td>
        </tr>
        <tr>
            <td class="col-xs-4"><b>Type: </b>{{ contract.get_type_display }}</td>
            <td class="col-xs-4"><b>Contract ID: </b>{{ contract.contract_id }}</td>
            <td class="col-xs-4"><b>Customer: </b>{{ contract.customer|default:"---------" }}</td>
        </tr>
        <tr><td colspan="3"><b>Description: </b>{{ contract.description|default:"---------" }}</td></tr>
        <tr><td colspan="3"><b>Notes: </b>{{ contract.notes|default:"---------" }}</td></tr>
    </table>
    <div class="row">
        <div class="col-xs-12">
            <hr>
            {% if not contract_ctx.invoices %}
            <p class="text-center"><b>No invoices for this contract.</b></p>
            {% endif %}
            {% if contract_ctx.invoices %}
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="col-xs-2 no-wrap">Invoice ID</th>
                    <th class="col-xs-2 no-wrap">Status</th>
                    <th class="col-xs-1 no-wrap">Expected Inv. Date</th>
                    <th class="col-xs-1 no-wrap">Expected Pay. Date</th>
                    <th class="col-xs-1 no-wrap">Actual Inv. Date</th>
                    <th class="col-xs-1 no-wrap">Actual Pay. Date</th>
                    <th class="col-xs-1 no-wrap">Expected Amount</th>
                    <th class="col-xs-1 no-wrap">Actual Amount</th>
                    <th class="col-xs-2 no-wrap">Actions</th>
                </tr>
                </thead>

                {% for invoice_ctx in contract_ctx.invoices %}
                {% with invoice=invoice_ctx.invoice %}
                <tr>
                    <td class="no-wrap">{{ invoice.invoice_id|default:"---------" }}</td>
                    <td class="no-wrap">{{ invoice.get_state_display }}</td>
                    <td class="no-wrap">{{ invoice.expected_invoice_date|date:"DATE_FORMAT" }}</td>
                    <td class="no-wrap">{{ invoice.actual_invoice_date|date:"DATE_FORMAT"|default:"---------" }}</td>
                    <td class="no-wrap">{{ invoice.expected_payment_date|date:"DATE_FORMAT" }}</td>
                    <td class="no-wrap">{{ invoice.actual_payment_date|date:"DATE_FORMAT"|default:"---------" }}</td>
                    <td class="no-wrap">{{ invoice.expected_amount|currency }}</td>
                    <td class="no-wrap"{{ invoice.actual_amount|currency|default:"---------" }}</td>
                    {% if is_manager %}
                    <td>
                        <form action="{{ invoice_ctx.delete_url }}" method="post">
                            {% csrf_token %}
                            <div class="btn-group btn-group-xs" style="display: flex;"> <!-- prevents button wrapping -->
                                {% if contract.state != contract.STATES.COMPLETE %}
                                <a class="btn btn-default" href="{{ invoice_ctx.update_url }}">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                {% endif %}

                                {% if contract.state == contract.STATES.NEW %}
                                <a class="btn btn-danger" data-toggle="modal" data-target="#action-modal"
                                 data-title="Confirm Deletion"
                                 data-body="Are you sure you want to delete invoice on <b>{{ invoice.expected_invoice_date|date }}</b> for contract <b>{{ contract.contract_id }}</b>?"
                                 data-btn-class="btn-danger" data-btn-text="Delete">
                                    <i class="fa fa-trash"></i>
                                </a>
                                {% endif %}
                                <a class="btn btn-primary" href="{{ invoice_ctx.print_url }}">
                                    <i class="fa fa-print"></i>
                                </a>
                            </div>
                        </form>
                    </td>
                    {% endif %}
                </tr>
                {% endwith %}
                {% endfor %}
            </table>
            {% endif %}

            {% if is_manager and contract.state == contract.STATES.NEW %}
            <p class="text-center">
                <a class="btn btn-sm btn-primary" href="{{ contract_ctx.invoice_url }}">Create Invoice</a>
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% endwith %}

{% endblock %}

src/labsite/templates/accounting/home.html
{% extends "accounting/base.html" %}

{% block nav-links-left %}{% endblock %}

{% block content %}

<div class="row">
    <div class="panel panel-default col-sm-offset-3 col-sm-6">
        <table class="table table-bordered" style="font-size: 1.5em;">
            <tbody>
            {% for business_unit in business_units %}
            <tr>
                <td>
                    <a href="{% url 'accounting:dashboard' business_unit=business_unit.pk %}">
                        {{ business_unit.name }} (Account {{ business_unit.account_number }})
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>
                    <div class="col-xs-12 text-center">
                        <h4 class="">You currently are not associated with any business units.</h4>
                    </div>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-3 col-sm-6 text-center">
        <a class="btn btn-primary" href={% url 'accounting:create_business_unit' %}>
            Create Business Unit <i class="fa fa-fw fa-plus-square" title="Add" aria-hidden="true"></i>
        </a>
    </div>
</div>

{% endblock %}

src/labsite/templates/accounting/nav_tabs.html
<div class="well nav-well">
<ul class="nav nav-tabs">
    <li {% if active == "dashboard" %}class="active"{% endif %}><a href={% url 'accounting:dashboard' business_unit=current_business_unit.pk %}>Dashboard</a></li>
    <li {% if active == "contracts" %}class="active"{% endif %}><a href={% url 'accounting:contracts' business_unit=current_business_unit.pk %}>Contracts</a></li>
    <li {% if active == "prospects" %}class="active"{% endif %}><a href={% url 'accounting:prospects' business_unit=current_business_unit.pk %}>Prospects</a></li>
    <li {% if active == "reconcile" %}class="active"{% endif %}><a href={% url 'accounting:reconcile' business_unit=current_business_unit.pk %}>Monthly Reconcile</a></li>
    {% if is_manager %}
        <li {% if active == "settings" %}class="active"{% endif %}><a href={% url 'accounting:business_unit_settings' business_unit=current_business_unit.pk %}>Settings</a></li>
    {% endif %}
</ul>
</div>

src/labsite/templates/accounting/settings.html
{% extends "accounting/base.html" %}

{% load staticfiles %}

{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/accounting/settings.css' %}"/>

    {% include "accounting/nav_tabs.html" with active="settings" %}

    <div class="container-fluid">
        <div class="row-fluid">

            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ current_business_unit }} Settings</h3>
                    </div>
                    {% block settings_nav %}
                    {% endblock %}
                </div>
            </div>

            <div class="col-md-9">
                {% block settings_content %}

                {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}