src/labsite/accounting/urls.py
# flake8: noqa
from django.conf.urls import url

from . import views


app_name = 'accounting'

urlpatterns = [

    # Accounting HomePage
    url(r'^$', views.HomePageView.as_view(), name='home'),

    # Dashboard Views
    url(r'^(?P<business_unit>\d+)/dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^(?P<business_unit>\d+)/dashboard/fy-(?P<fiscal_year>\d+)/$', views.DashboardView.as_view(), name='dashboard'),

    # Expense Views
    url(r'^(?P<business_unit>\d+)/reconcile/$', views.MonthlyReconcileView.as_view(), name='reconcile'),
    url(r'^(?P<business_unit>\d+)/reconcile/fy-(?P<fiscal_year>\d+)/$', views.MonthlyReconcileView.as_view(), name='reconcile'),

    # Contracts View
    url(r'^(?P<business_unit>\d+)/contracts/$', views.ContractsView.as_view(), name='contracts'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/$', views.ContractDetailView.as_view(), name='contract_detail'),

    # Prospects View
    url(r'^(?P<business_unit>\d+)/prospects/$', views.ProspectsView.as_view(), name='prospects'),

    # Settings Views
    url(r'^(?P<business_unit>\d+)/settings/business_unit/$', views.BusinessUnitSettingsPageView.as_view(), name='business_unit_settings'),
    url(r'^(?P<business_unit>\d+)/settings/user_team_roles/$', views.UserTeamRolesSettingsPageView.as_view(), name='user_team_roles_settings'),

    # Business Unit Forms
    url(r'^create/$', views.BusinessUnitCreateView.as_view(), name='create_business_unit'),
    url(r'^(?P<business_unit>\d+)/update/$', views.BusinessUnitUpdateView.as_view(), name='update_business_unit'),
    url(r'^(?P<business_unit>\d+)/delete/$', views.BusinessUnitDeleteView.as_view(), name='delete_business_unit'),

    # Contracts Forms
    url(r'^(?P<business_unit>\d+)/contracts/create/$', views.ContractCreateView.as_view(), name='create_contract'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/update/$', views.ContractUpdateView.as_view(), name='update_contract'),

    # Prospect Forms
    url(r'^(?P<business_unit>\d+)/prospects/create/$', views.ProspectCreateView.as_view(), name='create_prospect'),

    # Invoice Forms
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/create/$', views.InvoiceCreateView.as_view(), name='create_invoice'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/(?P<invoice>\d+)/update/$', views.InvoiceUpdateView.as_view(), name='update_invoice'),
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/(?P<invoice>\d+)/delete/$', views.InvoiceDeleteView.as_view(), name='delete_invoice'),

    # User Team Role Forms
    url(r'^(?P<business_unit>\d+)/user_team_role/create/$', views.UserTeamRoleCreateView.as_view(), name='create_user_team_role'),
    url(r'^(?P<business_unit>\d+)/user_team_role/(?P<user_team_role>\d+)/update/$', views.UserTeamRoleUpdateView.as_view(), name='update_user_team_role'),
    url(r'^(?P<business_unit>\d+)/user_team_role/(?P<user_team_role>\d+)/delete/$', views.UserTeamRoleDeleteView.as_view(), name='delete_user_team_role'),

    # Invoice Print Page
    url(r'^(?P<business_unit>\d+)/contracts/(?P<contract>\d+)/invoice/(?P<invoice>\d+)/print/$', views.InvoicePrintView.as_view(), name='print_invoice'),
]

src/labsite/foodapp/urls.py
from django.conf.urls import url

from . import views


app_name = 'foodapp'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),

    url(r'^billing/cards/$', views.StripeCardListView.as_view(), name='stripe_card_list'),
    url(r'^billing/cards/create$', views.StripeCreateView.as_view(), name='stripe_card_create'),
    url(r'^billing/cards/create$', views.StripeCreateView.as_view(), name='stripe_customer_create'),
    url(r'^billing/cards/delete/(?P<card_id>\w+)/$', views.StripeCardDeleteView.as_view(), name='stripe_card_delete'),
    url(r'^billing/cards/update/(?P<card_id>\w+)/$', views.StripeCardUpdateView.as_view(), name='stripe_card_update'),

    url(r'^billing/invoices/$', views.StripeInvoiceView.as_view(), name='stripe_invoices'),

    url(r'^burrito-projections/$', views.BurritoProjectionView.as_view(), name='burrito_projections'),

    url(r'^orders/$', views.OrderListView.as_view(), name='orders'),
    url(r'^orders/unpaid/$', views.UnpaidOrdersView.as_view(), name='unpaid_orders'),
    url(r'^orders/user/(?P<username>\w+)/$', views.UserOrderView.as_view(), name='user_orders'),
    url(r'^orders/last_month/$', views.last_month_view, name='last_month_view'),
    url(r'^orders/leaderboard/$', views.LeaderboardView.as_view(), name='leaderboard'),
    url(r'^orders/(?P<year>\d{4})/(?P<month>\d{2})/$', views.MonthOrdersView.as_view(), name='month_orders'),
    url(r'^orders/super/(?P<year>\d{4})/(?P<month>\d{2})/$', views.SuperMonthOrdersView.as_view(), name='super_month_orders'),  # noqa: E501
]

src/labsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = 'labsite/home.html'


urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='home'),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Auth urls
    url(r'^', include('labsite.accounts.auth.urls')),

    url(r'^accounts/', include('registration_invite.urls.activation')),

    # App urls
    url(r'^lunch/', include('labsite.foodapp.urls')),
    url(r'^worklog/', include('labsite.worklog.urls')),
    url(r'^accounting/', include('labsite.accounting.urls')),
]

src/labsite/worklog/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

from . import views
from .api import views as api_views


router = DefaultRouter()
router.register(r'workdays', api_views.WorkDayViewSet)
router.register(r'workitems', api_views.WorkItemViewSet)
router.register(r'users', api_views.UserViewSet)
router.register(r'jobs', api_views.JobViewSet)


DATEMIN = r'(?P<datemin>\d{4}-\d{2}-\d{2})'
DATEMAX = r'(?P<datemax>\d{4}-\d{2}-\d{2})'
# accepts:  date_date   or   date_   or   _date
DATERANGE1 = '(?:' + DATEMIN + '_' + DATEMAX + '?)'
DATERANGE2 = '(?:_' + DATEMAX + ')'

USERNAME = r'(?P<username>[a-zA-Z0-9]+)'
# JOBID = r'(?:_job_(?P<jobid>[0-9]+))'


app_name = 'worklog'

urlpatterns = [
    url(r'^$', views.HomepageView.as_view(), {}, name='home'),
    url(r'^(?P<date>\d{4}-\d{2}-\d{2})/$', views.WorkItemView.as_view(), name='date'),
    url(r'^today/$', views.CurrentDateRedirectView.as_view(), name='today'),
    url(r'^add/$', views.CurrentDateRedirectView.as_view(), name='add'),

    url(r'^view/$', views.WorklogView.as_view(), {}, name='view'),
    url(r'^view/today/$', views.WorklogView.as_view(), {'datemin': 'today', 'datemax': 'today'}, name='view-today'),

    url(r'^view/' + DATERANGE1 + '/$', views.WorklogView.as_view(), name='view-daterange'),
    url(r'^view/' + DATERANGE2 + '/$', views.WorklogView.as_view(), name='view-datemax'),
    url(r'^view/' + USERNAME + '/$', views.WorklogView.as_view(), name='view-user'),
    url(r'^view/' + USERNAME + '/today/$', views.WorklogView.as_view(), {'datemin': 'today', 'datemax': 'today'}, name='view-user-today'),  # noqa: E501
    url(r'^view/' + USERNAME + '/' + DATERANGE1 + '/$', views.WorklogView.as_view(), name='view-user-daterange'),
    url(r'^view/' + USERNAME + '/' + DATERANGE2 + '/$', views.WorklogView.as_view(), name='view-user-datemax'),

    url(r'^report/$', views.ReportView.as_view(), name='report_url'),
    url(r'^chart/$', views.ChartView.as_view(), name='chart_url'),
    url(r'^chart/job/$', views.JobDataView.as_view(), name='job_data_url'),

    url(r'^api/', include(router.urls)),
]

src/labsite/accounting/views.py
import json
from collections import OrderedDict
from datetime import date
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Sum
from django.db.models import Value as V
from django.db.models.functions import Coalesce
from django.db.transaction import atomic
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.utils.functional import cached_property
from django.utils.safestring import mark_safe
from django.views.generic import (
    CreateView, DeleteView, FormView, TemplateView, UpdateView,
)

from . import forms, models
from .utils import FiscalCalendar, Month, format_currency


class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal):
            return int(obj)
        return super(DecimalEncoder, self).default(obj)


class AccountingMixin(LoginRequiredMixin):
    """
    Common setup required for most accounting views.
    """
    success_url_name = None

    @atomic
    def dispatch(self, request, *args, **kwargs):
        return super(AccountingMixin, self).dispatch(request, *args, **kwargs)

    def get_fiscal_year(self, calendar_date):
        calendar_year = calendar_date.year

        # if we're in the first half of the calendar year, then we're in the previous fiscal year
        if calendar_date < date(calendar_year, 7, 1):
            return calendar_year - 1
        return calendar_year

    def get_object_fiscal_year(self):
        pass

    @cached_property
    def user(self):
        return self.request.user

    @cached_property
    def team_role(self):
        try:
            return models.UserTeamRole.objects.get(
                user=self.user,
                business_unit=self.current_business_unit,
            )
        except models.UserTeamRole.DoesNotExist:
            return None

    @cached_property
    def is_manager(self):
        if self.user.is_superuser:
            return True

        if self.team_role is None:
            return False

        ROLES = models.UserTeamRole.ROLES
        return self.team_role.role == ROLES.MANAGER

    @cached_property
    def business_units(self):
        return self.user.business_units.all()

    @cached_property
    def current_business_unit(self):
        pk = self.kwargs.get('business_unit', None)

        if pk is None:
            return None
        return models.BusinessUnit.objects.get(pk=pk)

    @cached_property
    def fiscal_calendar(self):
        fiscal_year = self.kwargs.get('fiscal_year')

        # coerce to int
        if fiscal_year is not None:
            fiscal_year = int(fiscal_year)

        # try to determine from the last reconcile date
        else:
            latest = models.MonthlyReconcile.objects \
                .filter(business_unit=self.current_business_unit) \
                .order_by('-year', '-month').first()

            if latest is not None:
                latest_date = Month.next(latest).as_date()  # Need to operate on next available month
                fiscal_year = FiscalCalendar.get_fiscal_year(latest_date)

        # if fiscal_year is none, will default to fiscal year for current date
        return FiscalCalendar(fiscal_year)

    @cached_property
    def fiscal_year(self):
        return self.fiscal_calendar.fiscal_year

    @cached_property
    def fiscal_months(self):
        return self.fiscal_calendar.months

    @cached_property
    def current_billing_month(self):
        """
        The current month to focus on for billing purposes. This will either be
        the next month to reconcile, or (if no months have been reconciled yet)
        the first month of this fiscal year.
        """
        latest = models.MonthlyReconcile.objects \
            .filter(business_unit=self.current_business_unit) \
            .order_by('-year', '-month').first()

        # get the next month
        if latest is not None:
            latest = Month(latest.year, latest.month)
            return Month.next(latest)

        # default to start of this fiscal year
        return Month(self.fiscal_calendar.start_date)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'business_units': self.business_units,
            'current_business_unit': self.current_business_unit,
            'fiscal_year': self.fiscal_year,
            'fiscal_start': self.fiscal_calendar.start_date,
            'fiscal_end': self.fiscal_calendar.end_date,
            'is_manager': self.is_manager,
        })

        return context

    def get_success_url_kwargs(self):
        return {
            'business_unit': self.current_business_unit.pk
        }

    def get_success_url(self):
        if self.success_url_name is None:
            return super().get_success_url()
        return reverse(self.success_url_name, kwargs=self.get_success_url_kwargs())


class ViewerMixin(AccountingMixin, UserPassesTestMixin):
    """
    View requires 'view' permissions
    """

    def test_func(self):
        if self.is_manager:
            return True

        if self.team_role is not None:
            ROLES = models.UserTeamRole.ROLES
            if self.team_role.role == ROLES.VIEWER:
                return True
        return False


class ManagerMixin(AccountingMixin, UserPassesTestMixin):
    """
    View requires 'edit' permissions
    """

    def test_func(self):
        return self.is_manager


class ContractCtxMixin(object):
    """
    Contract context functions to retreive context data
    """

    def make_contract_context(self, contract):
        url_kwargs = self.contract_url_kwargs(contract)

        return {
            'contract': contract,
            'invoices': [
                self.make_invoice_context(invoice) for invoice
                in models.Invoice.objects.filter(contract=contract).order_by('-expected_invoice_date')
            ],
            'update_url': reverse('accounting:update_contract', kwargs=url_kwargs),
            'invoice_url': reverse('accounting:create_invoice', kwargs=url_kwargs),
            'detail_url': reverse('accounting:contract_detail', kwargs=url_kwargs),
        }

    def make_invoice_context(self, invoice):
        url_kwargs = self.invoice_url_kwargs(invoice)
        return {
            'invoice': invoice,
            'delete_url': reverse('accounting:delete_invoice', kwargs=url_kwargs),
            'update_url': reverse('accounting:update_invoice', kwargs=url_kwargs),
            'print_url': reverse('accounting:print_invoice', kwargs=url_kwargs),
        }

    def contract_url_kwargs(self, contract):
        return {
            'business_unit': self.current_business_unit.pk,
            'contract': contract.pk
        }

    def invoice_url_kwargs(self, invoice):
        kwargs = self.contract_url_kwargs(invoice.contract)
        kwargs['invoice'] = invoice.pk

        return kwargs

    def activate(self, contract):
        if not contract.has_invoice():
            msg = "Contract %s not activated. Activation requires at least one invoice."
            messages.error(self.request, msg % contract.contract_id)

        elif not contract.amount_matches_invoices():
            msg = "Contract %s not activated. Sum of invoice amounts (%s) do not equal contract amount (%s)."
            messages.error(self.request, mark_safe(msg % (
                contract.contract_id,
                format_currency(contract.get_invoices_expected_total()),
                format_currency(contract.amount),
            )))

        else:
            contract.activate()
            contract.save()

    def complete(self, contract):
        if not contract.all_invoices_received():
            msg = "Contract %s not completed. Contract has unreceived invoices."
            messages.error(self.request, msg % contract.contract_id)

        else:
            contract.complete()
            contract.save()

    def delete(self, contract):
        if contract.state != contract.STATES.NEW:
            msg = "Contract %s not deleted. Cannot delete active/completed contracts."
            messages.error(self.request, msg % contract.contract_id)

        else:
            messages.success(self.request, "Contract '%s' was successfully deleted." % contract.name)
            contract.delete()


################################################################
# Dashboard Views                                              #
################################################################
class HomePageView(ViewerMixin, TemplateView):
    template_name = 'accounting/home.html'


class DashboardView(ViewerMixin, TemplateView):
    template_name = 'accounting/dashboard.html'

    def get_expected_monthly_invoices(self, date):
        # Although this call looks similar to the other queries, there may be multiple
        # invoices per month while the other models are an aggregate monthly balance.
        return models.Invoice.objects \
            .exclude(contract__state=models.Contract.STATES.NEW) \
            .filter(business_unit=self.current_business_unit) \
            .filter(expected_payment_date__year=date.year, expected_payment_date__month=date.month) \
            .aggregate(v=Coalesce(Sum('expected_amount'), V(0)))['v']

    def get_actual_monthly_invoices(self, date):
        # Although this call looks similar to the other queries, there may be multiple
        # invoices per month while the other models are an aggregate monthly balance.
        return models.Invoice.objects \
            .exclude(contract__state=models.Contract.STATES.NEW) \
            .filter(business_unit=self.current_business_unit) \
            .filter(actual_payment_date__year=date.year, actual_payment_date__month=date.month) \

src/labsite/templates/worklog/base.html
{% extends "base.html" %}
    
{% block title %}Worklog{% endblock %}

{% load staticfiles %}

{% block app-styles %}
<link href="{% static 'css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block app-scripts %}
<script>
    var worklog = {
        date: '{{ date.isoformat }}',
        csrfToken: '{{ csrf_token }}',
        username: '{{ user.username }}',
        userid: '{{ user.id }}',
    };
</script>

<script src="{% static 'js/lib/jquery.cookie.js' %}"></script>
<script src="{% static 'js/lib/jquery-ui-1.10.4.custom.min.js' %}"></script>
<script src="{% static 'js/lib/handlebars-v1.3.0.js' %}"></script>
{% endblock %}

{% block nav-links %}
{% if user.is_authenticated %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'worklog:today' %}">New Work Item</a></li>
    <li><a href="/worklog/chart">Chart</a></li>
    <li><a href="/worklog/view/{{ user }}">My Work</a></li>
</ul>
{% endif %}
{% endblock %}

src/labsite/templates/worklog/chart.html
{% extends "worklog/base.html" %}
{% load staticfiles %}

{% block content %}

    <script type="text/javascript" src="{% static 'js/lib/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lib/jquery.flot.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lib/jquery.flot.selection.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lib/jquery.flot.threshold.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lib/jquery.ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lib/chart.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/smoothness/smoothness.css' %}" />

    <script type="text/javascript">
        var c, options = {
            xaxis: {
                mode: 'time',
                timeformat: '%m-%d-%y'
            },
            yaxis: {
                label: 'Hours Available'
            }
        };

        var jobDataUrl = "{% url 'worklog:job_data_url' %}";
        var jobId = '';

        function parseData(data, status, xhr) {
            if('error' in data) {
                $('#plot').after('<div class="error">' + data['error'] + '</div>');
            } else {
                var arr = [],
                    keys = [],
                    count = 0,
                    positive,
                    negative,
                    changedGraph = false;

                //Grab the keys
                for(var d in data) {
                    keys.push(d);
                }

                //Sort the keys since they are not sorted
                //when returned from the python
                keys.sort();

                if(data[keys[0]] > 0) {
                    positive = true;
                    negative = false;
                } else {
                    positive = false;
                    negative = true;
                }

                for(var i = 0; i < keys.length; i++) {
                    var point = [new Date(keys[i]).getTime(), data[keys[i]]];
                    arr.push(point);

                    if(data[keys[i]] > 0) {
                        if(!positive) {
                            changedGraph = true;
                        }

                        positive = true;
                        negative = false;
                    } else {
                        if(!negative) {
                            changedGraph = true;
                        }

                        positive = false;
                        negative = true;
                    }
                }

                var chartingData = {
                    data: arr,
                    threshold: { below: 0, color: '#FF0000' }
                };

                c = new Chart('#plot', [chartingData], options);

                if($('#overview').children().length) {
                    c.disableOverview();
                }

                c.displayLineChart();
                c.enableOverview('#overview');

                drawAxes();

                function respectYAxis() {
                    var changed = true;

                    if($('#y-axis').attr('checked')) {
                        if(!changedGraph) {
                            if(negative) {
                                options.yaxis.max = 0;
                            } else {
                                options.yaxis.min = 0;
                            }
                        } else {
                            if('min' in options.yaxis) {
                                delete options.yaxis.min
                            }

                            if('max' in options.yaxis) {
                                delete options.yaxis.max;
                            }

                            changed = true;
                        }
                    } else {
                        if('min' in options.yaxis) {
                            delete options.yaxis.min;
                        } else if('max' in options.yaxis) {
                            delete options.yaxis.max;
                        } else {
                            changed = false;
                        }
                    }

                    if(changed) {
                        c.changeOptions(options);
                        c.displayLineChart();
                        drawAxes();
                    }
                }

                function respectTooltips() {
                    if($('#tooltips').attr('checked')) {
                        c.enableTooltips();
                    } else {
                        c.disableTooltips();
                    }
                }

                //Register the y-axis listener
                $('#y-axis').click(respectYAxis);

                //Register the tooltips listener
                $('#tooltips').click(respectTooltips);

                //Handle the y-axis checkbox right after charting
                respectYAxis();

                //Handle the tooltips checkbox right after charting
                respectTooltips();
            }
        }

        function drawAxes() {
            $('canvas.overlay').attr('height', '550');
            var context = $('canvas.overlay')[0].getContext('2d');
            context.fillStyle = '#000';
            context.font = 'bold 12px sans-serif';
            context.textAlign ='center';
            context.fillText('Days', 275, 515);
            context.rotate(90 * Math.PI / 180);
            context.fillText('Available hours', 235, -3);
        }

        $(document).ready(function() {
            $('#startDate').datepicker({
                format: 'mm/dd/yy'
            });

            $('#endDate').datepicker({
                format: 'mm/dd/yy'
            });

            $('#chartingForm').submit(function(e) {
                e.preventDefault();
                e.stopPropagation();

                $('div.error').remove();

                if($('#jobs').val() === '-1') {
                    $('#plot').after('<div class="error">Select a job</div>');
                } else {
                    jobId = $('#jobs > optgroup > option:selected').val();
                    $.post('', $(this).serialize(), parseData, 'json');
                }
            });
        });
    </script>

    <style type="text/css">
        .label {
            -o-transform:rotate(-90deg);
            -moz-transform: rotate(-90deg);
            -webkit-transform:rotate(-90deg);
            filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
        }
        .error {
            color: #FF0000;
            margin-bottom: 3px;
        }
        #options {
            margin: 30px 0px;
        }
    </style>
</head>


{% if error %}
<div class="error">
    {{ error }}
</div>
{% endif %}
{% if job_id %}
    <script type="text/javascript">
        $(document).ready(function() {
            jobId = '{{ job_id }}'
            $('#jobs > optgroup > option[value={{ job_id }}]').attr('selected', 'selected');
            $('#chartingForm').submit();
        });
    </script>
{% endif %}
<form id="chartingForm" method="post" target="">
    {% csrf_token %}
    <select id="jobs" name="job_id">
        <option value="-1">-- Select a Job --</option>
        <optgroup label="Open Jobs">
            {% for job in open_jobs %}
            <option value="{{ job.pk }}">{{ job }}</option>
            {% endfor %}
        </optgroup>
        <optgroup label="Closed Jobs">
            {% for job in closed_jobs %}
            <option value="{{ job.pk }}">{{ job }}</option>
            {% endfor %}
        </optgroup>
    </select>
    <br />
    <label for="startDate">Start Date (mm/dd/yyyy)</label>
    <input type="text" id="startDate" name="start_date" value="" /><br />
    <label for="endDate">End Date (mm/dd/yyyy)</label>
    <input type="text" id="endDate" name="end_date" value="" /><br />
    <input type="submit" value="Submit" />
</form>
<div id="options">
<label for="y-axis">Show Y-Axis</label>
<input type="checkbox" id="y-axis" /><br />
<label for="tooltips">Show Worklog Entries</label>
<input type="checkbox" id="tooltips" /><br />
<div id="overview" style="margin-top: 15px; width: 300px; height: 80px; float: left"></div>
</div>

<div id="plot" style="width: 550px; height: 500px; float: left; margin: 0px 20px 0px 10px"></div>

{% endblock %}

src/labsite/templates/worklog/home.html
{% extends "worklog/base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="row">
        <div id="work-pane" class="col-sm-offset-3 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">Work</div>
                <div class="panel-body">
                    <h3 style="text-align: center">{{ total_hours }} hours worked this week</h3>
                </div>
                <table class="table table-bordered">
                    {% for datestring, date, hours, show_link in past_seven_days %}
                        <tr style="{%if 'Saturday' in datestring %}border-bottom: 2px solid gray;{% else %}{% endif %}">
                            {% if "Saturday" in datestring or "Sunday" in datestring %}
                                <th class="col-xs-6 text-center text-muted">{{ datestring }}</th>
                            {% else %}
                                <th class="col-xs-6 text-center">{{ datestring }}</th>
                            {% endif %}
                            <td class="col-xs-6 text-center">
                                {{ hours }}
                                {% if show_link %}&nbsp;<small>(<a href="{% url 'worklog:date' date %}">Log Work</a>)</small>{% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/labsite/templates/worklog/report.html
{% extends "worklog/base.html" %} {% block content %}

<!-- Content -->
<div class="content">
    {% if error %} {{ error }} {% endif %} {% if generated %}
    <h1>An invoice was generated and emailed to you</h1>
    {% endif %} {% if invoiced %}
    <h1>All un-invoiced items have now been invoiced</h1>
    {% endif %}
    <form method="post" action="">
        {% csrf_token %}
        <input type="hidden" name="date" value="{{ date }}" />
        <button type="submit" name="generate" value="generate" class="btn btn-primary">Generate report</button>
        <button type="submit" name="invoice" value="invoice" class="btn btn-primary">Invoice all items</button>
    </form>
</div>

{% endblock %}

src/labsite/templates/worklog/viewwork.html
{% extends "worklog/base.html" %} {% block content %}

<div class="row">
    <br>

    <!-- Content -->
    <div class="col-md-9">
        {% include worklog_data_template %}
        <!-- Contents of the current query -->
        <p style="margin-bottom: 0em;">Current query:</p>
        <table style="margin-left: 3em;">
            {% if current_filters %} {% for key,val in current_filters %}
            <tr>
                <td>{{ key }}:</td>
                <td>{{ val }}</td>
            </tr>
            {% endfor %} {% else %}
            <tr>
                <td>Showing all work items.</td>
            </tr>
            {% endif %}
        </table>

    </div>

    <!-- Sidebar -->
    <div class="col-md-3">
        {% for submenu in filtermenu %} {% if submenu.name %}
        <h3>By {{ submenu.name }}</h3>{% endif %}
        <ul>
            {% for item in submenu.items %}
            <li><a href="{{ menulink_base }}?{{ item.querystring }}">{{ item.name }}</a>
            </li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>

</div>

{% endblock %}

src/labsite/templates/worklog/viewwork_data.html
{% if items %}
<table class="table table-bordered">
    <thead>
        <th class="col-xs-2">User</th>
        <th class="col-xs-3">Date</th>
        <th class="col-xs-2">Job</th>
        <th class="col-xs-1">Hours</th>
        <th class="col-xs-4">Text</th>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.user }}</td>
            <td>{{ item.date }}</td>
            <td>{{ item.hours }}</td>
            <td>{{ item.job }}</td>
            <td class="preserve-newLine">{{ item.text }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
<p>No work accomplished... this is terrible!</p>
{% endif %}